name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: libretro

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: makefile.libretro
      run: make -f "Makefile.libretro" clean
    - name: make check
      run: make -f "Makefile.libretro" check
    - name: make distcheck
      run: make -f "Makefile.libretro" distcheck
